// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk9gbAimjshbGAHWT9aaXZIWxVo3Ncp6o',
    appId: '1:1049520392597:web:31e446153ca3a3f6054e9c',
    messagingSenderId: '1049520392597',
    projectId: 'evspots-app',
    authDomain: 'evspots-app.firebaseapp.com',
    databaseURL: 'https://evspots-app-default-rtdb.firebaseio.com',
    storageBucket: 'evspots-app.appspot.com',
    measurementId: 'G-4P1VQ93317',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnT4iva6nwhpMH334T0wZM-1BpCakXMUk',
    appId: '1:1049520392597:android:4ff2fa7c10575afd054e9c',
    messagingSenderId: '1049520392597',
    projectId: 'evspots-app',
    databaseURL: 'https://evspots-app-default-rtdb.firebaseio.com',
    storageBucket: 'evspots-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDppZdHFghfNJqTEHYDs7WpjDgI-w8eS3Y',
    appId: '1:1049520392597:ios:9ba65a7d9fc558dc054e9c',
    messagingSenderId: '1049520392597',
    projectId: 'evspots-app',
    databaseURL: 'https://evspots-app-default-rtdb.firebaseio.com',
    storageBucket: 'evspots-app.appspot.com',
    androidClientId: '1049520392597-ru2om2pii9ni26o4j0rotlm69q5jrvo7.apps.googleusercontent.com',
    iosClientId: '1049520392597-9538o7glkskk9ch6kgtha4q288nlvn7e.apps.googleusercontent.com',
    iosBundleId: 'app.evspots',
  );
}
